//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int taskid { get; set; }
        public string description { get; set; }
        public System.DateTime duedate { get; set; }
        public bool status { get; set; }
    }
}
